package array_String_Demo;

public class StringClassMethods {

	public static void main(String[] args)
	{

		/*
		 * String is immutable class in java
		 * Ways
		 * --------
		 * 1.Using literal ---create one object inside SCP(String constant pool)
		 * 2.Using new keyword---creates two objects (SCP and JVM Heap)
		 * 
		 * for operations on String we use Methods
		 * but to compare IDs generated by Jvm for Object we use operators
		 * 
		 */

		String s1="Hello";
		
		String s2=new String("Hello");
		
		//object id
		System.out.println(s1==s2);//no false
		
		String s3="Hello";
		System.out.println(s1==s3);//true
		
		//String is immutable
		s1=s1+"Welcome";//for change it creates new object
		
		System.out.println(s1==s3);//false
		
		
		System.out.println("******String class Methods*************");
		
		String s4="Hello All";
		//length()
		System.out.println("Length of String: length(): "+s4.length());//9
		
		
		//toUpperCase() toLowerCase()
		System.out.println(s4.toUpperCase());
		System.out.println(s4.toLowerCase());
		
		//charAt(index)
		System.out.println("character at index 6 is: "+s4.charAt(6));//A
		
		//indexOf(char)
		System.out.println("index of char A: "+s4.indexOf('A'));//6
		System.out.println("index of char l: "+s4.indexOf('l'));//first occurance index
		
		/*
		 * How to test equality between strings
		 * 1.equals(): exact matching it is case sensitive
		 * 
		 * 2.equalsIgnoreCase()
		  */
		 
		String act="Selenium WebDriver is WEBUI automation library.";
		
		String exp="Selenium WebDriver is webui automation library/tool";
		System.out.println("using equals(): "+act.equals(exp));//true--false
		System.out.println("Using equalsIgnoreCase(): "+act.equalsIgnoreCase(exp));//true
		
		//trim() - ignore white space from before and after the string
			
		String s5="       Welcome        ";
		System.out.println(s5);
		System.out.println(s5.trim());
		
		//contains()=partail matching
		System.out.println("is exp string contains tool?: "+exp.contains("tool"));//true
		System.out.println("is exp string contains testNG?: "+exp.contains("testNG"));//false
		
		
		//startsWith(prefix value)
		System.out.println("Is exp string starts with Selenium?: "+exp.startsWith("Selenium"));//true
		System.out.println("Is string starts with Sel?: "+exp.startsWith("Sel"));//true
		System.out.println("Is String starts with nium?: "+exp.startsWith("nium"));//false
		
		
		//endsWith(Suffix value)
		System.out.println("Is exp string ends with library/tool: "+exp.endsWith("library/tool"));//true
		System.out.println("Is exp string ends with tool: "+exp.endsWith("tool"));//true
		System.out.println("Is exp string ends with library: "+exp.endsWith("library"));//false

		//concat() or  +
		String s6="Hi";
		String s7="How are you?";
		
		System.out.println(s6+" "+s7);
		System.out.println(s6.concat(" "+s7));
		
		//substring(index) subString(start, end)
		String s8="Automation Testing";
		System.out.println(s8.substring(11));//Testing
		System.out.println(s8.substring(0,10)); //Automation
		
		//split(regular expression)-pattern matching
		String tools="Selenium,TestNG,Maven,Jenkins,Appium";
		System.out.println(tools);
		
		String arr[]=tools.split(",");
		
		for(String i:arr)
		{
			
			System.out.println(i);
		}
		
		
		//single object
		String tool=tools.split(",")[2];
		System.out.println(tool);//Maven
		
		String date="Feb 2024";
		System.out.println(date);
		String month=date.split(" ")[0];
		String year=date.split(" ")[1];
		
		System.out.println(month);
		System.out.println(year);
		
		/*
		 * test product price is 1000(int) only
		 */
		String status="Product price is 1000 for order!";
		String amount=status.split(" ")[3];
		//string to integer-->Wrapper class
		int amt=Integer.parseInt(amount);
		//validation
		if(amt==1000)
		{
			System.out.println("Test pass!");
		}else
		{
			System.out.println("Test Fail!");
		}
		
	
		//replace()
		
		String str1="oooooo-hhhhhh-sssss-ooooo";
		System.out.println("Original String: "+str1);
		String res=str1.replace('o','p');
		System.out.println("Updated String: "+res);
		
		//toCharArray()-convert string into char array
		
		String str2="Hello";
		char ch[]=str2.toCharArray();
		
		for(char i:ch)
		{
			System.out.println(i);
		}
		
		
		
		
		//isEmpty()
		String str3="Welcome!";
		System.out.println(str3.isEmpty());//false
		String str4="";
		System.out.println(str4.isEmpty());//true
		
		
		/*
		 * StringBuffer and StringBuilder class
		 * StringBuffer is thread safe and builder is not a thread safe
		 * 1.These classes are mutable
		 * 2.It follows new keyword way
		 * 
		 * To reverse string using method-reverse()
		 */
		
		StringBuilder st=new StringBuilder("Hello");
		System.out.println(st);
		st.append("Everyone!");
		System.out.println(st);
		
		
		st.reverse();
		
		System.out.println(st);
		
		
		
		//String is immutable
//		String ss1="Hello";//object id=20
//		ss1=ss1+" All";//object id=25
//		System.out.println(ss1);
		//write a program to reverse a string without method in java
		String ss1="Java selenium";
		String res1="";
		
		for(int i=ss1.length()-1;i>=0;i--)
		{
			res1=res1+ss1.charAt(i);
		}
		
		System.out.println(res1);
		
		
		//toString()=String representation for any Object
		
		Integer num=1000;
		System.out.println(num);//1000
		System.out.println(num+90);//1090

		String data=num.toString();
		System.out.println(data+90);//100090
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
	
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
	}

}
